[package]
name = "master_node"
version = "0.1.0"
edition = "2021"

[dependencies]

sqlx = { version = "0.8.3", features = ["runtime-tokio-native-tls", "sqlite"] }
tokio = { version = "1", features = ["full"] }
reqwest = "0.12.12"